# adapted from https://github.com/r-spatial/sf/blob/main/.github/workflows/rcmdcheck.yml, March 29, 2023

name: R-CMD-check

on:
  push:
  pull_request:
    branches:
      - master
      - dev


jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest, r: 'release'}

    # env:
    #   R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    #   CRAN: ${{ matrix.config.cran }}

    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: 'recursive'

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          rtools-version: '42'
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Brew and macOS config
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config
          brew install udunits
          brew install netcdf
          brew install sqlite
          brew install curl
          brew install libgit2
          brew install imagemagick@6
          brew install gdal proj geos

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
